site_name: Engineering Knowledge Base
site_url: https://kelvinlee97.github.io/engineering/
repo_name: kelvinlee97/engineering
repo_url: https://github.com/kelvinlee97/engineering
docs_dir: .pages-build
site_dir: .pages-site
use_directory_urls: true

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - pymdownx.superfences
